```yaml
name: Frontend CI

on:
  push:
    paths:
      - "Frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: react-runner

    defaults:
      run:
        working-directory: Frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
```
